# Generated by Django 2.2.7 on 2019-12-02 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='SOME STRIN', max_length=50)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
