# Generated by Django 2.2.7 on 2019-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.CharField(default='SOME ', max_length=50),
        ),
    ]
