# Generated by Django 2.2.7 on 2019-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191202_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classes',
            field=models.BooleanField(default=False),
        ),
    ]
