# Generated by Django 2.2.7 on 2019-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fm',
            field=models.BooleanField(default=False),
        ),
    ]
